package exception.practice.task2;

/**
 * Created by Admin on 23.10.16.
 */
public class Main {
}
